name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # Runs CI checks.
  #
  # Violations are reported inline with annotations.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Install Node.
  # - Install Node dependencies.
  # - Start WordPress env.
  # - Run Cypress tests.
  # - Sets up PHP.
  # - Logs debug information.
  # - Logs PHP_CodeSniffer debug information.
  # - Runs PHPCS on the full codebase with warnings suppressed.
  # - Runs PHPCS on the `tests` directory without warnings suppressed.
  # - todo: Configure Slack notifications for failing scans.
  cd:
    name: Continuous Integration
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Setup WordPress env
        run: |
          npx wp-env start
      
      - name: Run Cypress tests
        run: |
          cp cypress.json.example cypress.json
          npx cypress run --config video=false

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - name: Log debug information
        run: |
          php --version
          composer --version

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-suggest --no-progress --no-ansi --no-interaction
          echo "vendor/bin" >> $GITHUB_PATH

      - name: Log PHPCS debug information
        run: phpcs -i

      - name: Run PHPCS on all Core files
        run: vendor/bin/phpcs . -q -n --report=checkstyle | cs2pr
